version: '3.8'

services:
  web:
    build: .
    container_name: galibat_web
    command: python src/manage.py runserver 0.0.0.0:18200
    volumes:
      - .:/app
    ports:
      - "18200:18200"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: galibat_db
    restart: always
    environment:
      POSTGRES_USER: galibat
      POSTGRES_PASSWORD: galibat_pass
      POSTGRES_DB: galibat_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "18205:5432"

volumes:
  postgres_data:
